networks:
  docker.network:
    driver: bridge

services:
  traefik:
    container_name: docker.traefik
    restart: unless-stopped
    image: traefik:v3
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entryPoints.ws.address=:9002
      - --entryPoints.wss.address=:9001
      - --providers.file.directory=/certs
      - --providers.file.watch=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefik.com`)
    networks:
      - docker.network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "9091:9001"
      - "9092:9002"
    volumes:
      # Mount the directory containing the certs
      - ./docker/traefik/:/certs/
      - ./docker/traefik/traefik.yaml:/certs/traefik.yaml
      # - ./docker/traefik/:/etc/traefik/dynamic/
      - /var/run/docker.sock:/var/run/docker.sock

  admin:
    build:
      context: ./docker/apache
      dockerfile: ./admin.dockerfile

    env_file: "./admin_html/docker.env"
    restart: unless-stopped
    container_name: docker.admin
    tty: true
    networks:
      - docker.network
    volumes:
      - ./admin_html:/var/www/html/
    labels:
      - traefik.http.routers.admin.rule=PathPrefix(`/--/admin`)
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.priority=800

  profile:
    build:
      context: ./docker/apache
      dockerfile: ./profile.dockerfile

    env_file: "./profile_html/docker.env"
    restart: unless-stopped
    container_name: docker.profile
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - ./profile_html:/var/www/html/
    labels:
      - traefik.http.routers.profile.rule=PathPrefix(`/--/profile`)
      - traefik.http.routers.profile.tls=true
      - traefik.http.routers.profile.priority=600

  tracker:
    build:
      context: ./docker/apache
      dockerfile: ./tracker.dockerfile

    env_file: "./tracker_html/docker.env"
    restart: unless-stopped
    container_name: docker.tracker
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - ./tracker_html:/var/www/html/
    labels:
      - traefik.http.routers.tracker.rule=PathPrefix(`/--/tracker`)
      - traefik.http.routers.tracker.priority=700
      - traefik.http.routers.tracker.tls=true

  website:
    build:
      context: ./docker/apache
      dockerfile: ./public.dockerfile

    env_file: "./public_html/docker.env"
    restart: unless-stopped
    container_name: docker.public
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - ./public_html:/var/www/html/
    labels:
      - traefik.http.routers.secure.rule=HostRegexp(`^.+\.eventlab\.com$`)
      - traefik.http.routers.secure.priority=300
      - traefik.http.routers.secure.tls=true
      - traefik.http.routers.public.rule=PathPrefix(`/`)
      - traefik.http.routers.public.priority=100

  ratchet:
    build:
      context: ./docker/apache
      dockerfile: ./ratchet.dockerfile

    restart: unless-stopped
    container_name: docker.ratchet
    tty: true
    ports:
      - "9001:9001"
      - "9002:9002"
    networks:
      - docker.network
    volumes:
      - ./docker/traefik/:/certs/
      - ./websocket:/var/www/html/
    labels:
      - traefik.enable=true
      # backend port
      # - traefik.http.services.ws-service.loadbalancer.server.port=9001
      # ws
      - traefik.http.routers.ws-service-ws.rule=Host(`eventlab.com`)
      - traefik.http.routers.ws-service-ws.entrypoints=ws
      - traefik.http.routers.ws-service-ws.priority=400
      # wss
      - traefik.http.routers.ws-service-wss.rule=Host(`eventlab.com`)
      - traefik.http.routers.ws-service-wss.entrypoints=wss
      - traefik.http.routers.ws-service-wss.tls=true
      - traefik.http.routers.ws-service-wss.priority=500
      # - traefik.http.routers.ws-service-wss.tls.certresolver=dns

  mysql:
    image: arm64v8/mysql:latest
    platform: linux/arm64
    restart: unless-stopped
    container_name: docker.mysql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - docker.network
    volumes:
      - "./docker/mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-localhost}


  redis:
    image: bitnami/redis:latest
    env_file: "./profile_html/docker.env"

    restart: unless-stopped
    container_name: docker.redis
    tty: true
    ports:
      - "6379:6379"
    networks:
      - docker.network
    volumes:
      - ./docker/redis:/bitnami/redis/data
      - ./docker/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

    # command: /bin/sh -c "redis-server --requirepass $$REDIS_ROOT_PASSWORD && redis-server /usr/local/etc/redis/redis.conf"
    command: >
      /bin/sh -c "redis-server /usr/local/etc/redis/redis.conf --requirepass $$REDIS_ROOT_PASSWORD"
      && sudo sysctl -w vm.overcommit_memory=1

    environment:
      ALLOW_EMPTY_PASSWORD: ${REDIS_ALLOW_EMPTY_PASSWORD:-no}


