---
    label: Profiles
    dependancy: sys_projects

    tablename: profiles

    columns:
        id:         incremental
        handle:     handle
        cmne:       mnemonic
        project:    base1

        is_contact:      boolean

        visitcount:      int
        firstvistcode:   date-code # day of year - year  142-24
        firstvistdate:   timestamp-null
        lastvistcode:    date-code
        lastvistdate:    timestamp-null

        created_at:    timestamp-null
        deleted_at:    timestamp-null

    seeds: owners
