<?php

$places = [
    'Alkmaar'             => 'Noord-Holland',
    'Almere'              => 'Flevoland',
    'Alphen aan den Rijn' => 'Zuid-Holland',
    'Amersfoort'          => 'Utrecht',
    'Amsterdam'           => 'Noord-Holland',
    'Apeldoorn'           => 'Gelderland',
    'Arnhem'              => 'Gelderland',
    'Breda'               => 'Noord-Brabant',
    'Delft'               => 'Zuid-Holland',
    'Haag Den Haag'       => 'Zuid-Holland',
    'Deventer'            => 'Overijssel',
    'Dordrecht'           => 'Zuid-Holland',
    'Ede'                 => 'Gelderland',
    'Eindhoven'           => 'Noord-Brabant',
    'Emmen'               => 'Drenthe Drenthe',
    'Enschede'            => 'Overijssel',
    'Groningen'           => 'Groningen',
    'Haarlemmermeer'      => 'Noord-Holland',
    'Haarlem'             => 'Noord-Holland',
    's-Hertogenbosch'     => 'Noord-Brabant',
    'Leeuwarden'          => 'Friesland',
    'Leiden'              => 'Zuid-Holland',
    'Maastricht'          => 'Limburg',
    'Nijmegen'            => 'Gelderland',
    'Rotterdam'           => 'Zuid-Holland',
    'Tilburg'             => 'Noord-Brabant',
    'Utrecht'             => 'Utrecht',
    'Venlo'               => 'Limburg',
    'Westland'            => 'Zuid-Holland',
    'Zaanstad'            => 'Noord-Holland',
    'Zoetermeer'          => 'Zuid-Holland',
    'Zwolle'              => 'Overijssel',
];
