<?php

$streets = [
    'De Ruijterkade',
    'Oosterdokskade',
    'Prins Hendrikkade',
    'Houtkopersdwarsstraat',
    'Buiten Bantammerstraat',
    'Schippersstraat',
    'Kalkmarkt',
    'Binnenkant',
    'Kromme Waal',
    'Oude Waal',
    'Binnen Bantammerstraat',
    'Nieuwe Jonkerstraat',
    'Nieuwe Ridderstraat',
    'Parkzichtlaan',
    'Zakkendragerssteeg',
    'Oudegracht',
    'Oudegracht aandeWerf',
    'Zakkendragershof',
    'Hekelsteeg',
    'Vredenburg',
    'Drieharingstraat',
    'Lange Viestraat',
    'Jacobskerkhof',
    'Hollandse Toren',
    'Rozenstraat',
    'Waterstraat',
    'Varkenmarkt',
    'Jacobskerksteeg',
    'Stationstraverse',
    'Stationspassage',
    'Radboudkwartier',
    'Theodorahof',
    'Rieteweg',
    'Willemskade',
    'Emmastraat',
    'Veemarkt',
    'Harm Smeengekade',
    'Touwslagerij',
    'Meeuwenlaan',
    'Lijnbaan',
    'Burgemeester Vos de Waelstraat',
    'Hoogstraat',
    'Grote Baan',
    'Kleine Baan',
    'Kleine Voort',
    'Mussenhage',
    'Pannekoekendijk',
    'Katerdijk',
    'Reigerstraat',
    'Leeuwerikstraat',
    'Kievitstraat',
    'Katwolderplein',
    'Nachtegaalstraat',
    'Merelstraat',
    'Westerlaan',
    'Westerstraat',
    'Roopoort',
    'Parkstraat',
    'Parkweg',
    'Emmawijk',
    'Burgemeester van Roijensingel',
    'Zeven Alleetjes',
];
