---
    id:         (auto)
    handle:     (auto)
    name:       result--tags
    table:      results
    label:      Tags
    cmne:       RTAG
    column:     tags
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--consents
    table:      results
    label:      Consents
    cmne:       RCST
    column:     consents
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--segments
    table:      results
    label:      Segments
    cmne:       RSEG
    column:     segments
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--journeys
    table:      results
    label:      Journeys
    cmne:       RJRN
    column:     journeys
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--labels
    table:      results
    label:      Labels
    cmne:       RLBL
    column:     labels
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--scores
    table:      results
    label:      Scores
    cmne:       RSCR
    column:     scores
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--utms
    table:      results
    label:      UTMs
    cmne:       RUTM
    column:     utms
    datatype:   concat
    valuetype:  single
---
    id:         (auto)
    handle:     (auto)
    name:       result--mails
    table:      results
    label:      Mails
    cmne:       RMLS
    column:     mails
    datatype:   concat
    valuetype:  single
